# Copyright © 2025 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

steps:
  - name: 'gcr.io/cloud-builders/mvn:3.8-jdk-8'
    id: maven-package
    entrypoint: 'mvn'
    args:
      - -B
      - -U
      - clean
      - package
      - -DskipTests

  - name: 'gcr.io/cloud-builders/mvn:3.8-jdk-8'
    id: deploy-to-artifact-registry
    entrypoint: 'mvn'
    args:
      - 'deploy'
      - '-Dmaven.wagon.http.google.EffectiveVersion=1.0.1'
    waitFor: ['maven-package']

  - name: 'bash'
    id: create-exit-gate-manifest
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        MANIFEST_FILE="/workspace/exit_gate_manifest.textproto"
        echo '# -*- protobuffer -*-' > "$${MANIFEST_FILE}"
        echo '# proto-file: security/opensource/exit_gate_v1/onboarded/proto/publishing_manifest.proto' >> "$${MANIFEST_FILE}"
        echo '# proto-message: PublishingManifest' >> "$${MANIFEST_FILE}"
        echo '' >> "$${MANIFEST_FILE}"
        echo 'publish_all: true' >> "$${MANIFEST_FILE}"
        echo "Created manifest file: $${MANIFEST_FILE}"
    waitFor: ['deploy-to-artifact-registry']

  - name: 'gcr.io/cloud-builders/gsutil'
    id: upload-exit-gate-manifest
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        GCS_MANIFEST_DIR="gs://oss-exit-gate-prod-projects-bucket/cloud-data-fusion/mavencentral/manifests/"
        MANIFEST_FILE="/workspace/exit_gate_manifest.textproto"
        # Use a timestamp to create a unique manifest filename for each release
        MANIFEST_FILENAME="release_$(date -u +%Y%m%d%H%M%S).textproto"

        echo "Uploading manifest to $${GCS_MANIFEST_DIR}$${MANIFEST_FILENAME}"
        gsutil cp "$${MANIFEST_FILE}" "$${GCS_MANIFEST_DIR}$${MANIFEST_FILENAME}"
        echo "Manifest uploaded successfully. OSS Exit Gate process should now be triggered."
    waitFor: ['create-exit-gate-manifest']

options:
  requestedVerifyOption: VERIFIED
  machineType: 'E2_HIGHCPU_32'
